apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: LOG_LEVEL
        - name: DEFAULT_COLOR
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: DEFAULT_COLOR
        - name: DB_HOST
          value: {{ .Values.database.host }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: password
        - name: DB_NAME
          value: {{ .Values.database.name }}
      volumes:
      - name: log-volume
        emptyDir: {}

