apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Chart.Name }}-mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:{{ .Values.mysql.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: {{ .Values.database.name }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        emptyDir: {}

