name: Docker Image CI

on:
  push:
    branches: 
      - "testing"
    paths:
      - "app.py"
      - "index.html"
  pull_request:
    branches: 
      - "main"
    paths:
      - "app.py"
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask-color-changer:$(date +%s)

    - name: Push the Docker image to Docker Hub
      run: |
        docker tag flask-color-changer:$(date +%s) akhil1993/flask-color-changer:latest
        docker push akhil1993/flask-color-changer:latest
